import { test } from 'vitest'
import { createWorkspace, runCli } from './cli.js'

interface LanguageCase {
  readonly name: string
  readonly files: Readonly<Record<string, readonly string[]>>
  readonly status: number
  readonly stdout?: readonly string[]
  readonly stderr?: readonly string[]
}

const cases: readonly LanguageCase[] = [
  {
    name: 'TypeScript comments of every kind are reported',
    files: {
      'bad.ts': [
        '// @ts-expect-error',
        "const a: number = 'x'",
        '/** JSDoc */',
        'export const b = a /* trailing */',
        '/* c8 ignore next */',
        '// eslint-disable-next-line',
        'export const c = `${b /* inside */}`',
        '/// <reference types="node" />',
      ],
      'bad.tsx': ['export const A = () => (', '  <div>', '    {/* jsx */}', '  </div>', ')'],
      'bad.mjs': ['/** @type {number} */', 'export const d = 1'],
    },
    status: 1,
    stdout: [
      'bad.mjs:1:1: JavaScript comment',
      'bad.ts:1:1: TypeScript comment',
      'bad.ts:3:1: TypeScript comment',
      'bad.ts:4:20: TypeScript comment',
      'bad.ts:5:1: TypeScript comment',
      'bad.ts:6:1: TypeScript comment',
      'bad.ts:7:23: TypeScript comment',
      'bad.ts:8:1: TypeScript comment',
      'bad.tsx:3:6: TypeScript comment',
    ],
  },
  {
    name: 'TypeScript and JavaScript strings, templates, regexes and JSX text are not comments',
    files: {
      'clean.ts': [
        'const url = "http://x"',
        "const block = '/* x */'",
        'const template = `/* x */ ${url} // y`',
        'const regex = /\\/\\/x/',
        'const ratio = 4 / 2 / 1',
        'export { url, block, template, regex, ratio }',
      ],
      'clean.jsx': ['export const A = () => <a href="http://x">// text /* text */</a>'],
      'clean.cjs': ['module.exports = { pattern: /[/*]/g, escaped: "\\"//" }'],
    },
    status: 0,
  },
  {
    name: 'TypeScript shebang and leading reference directives are allowed',
    files: {
      'allowed.ts': [
        '#!/usr/bin/env node',
        '/// <reference types="node" />',
        '/// <reference lib="es2025" />',
        'export {}',
      ],
      'allowed.mjs': ['#!/usr/bin/env node', 'export {}'],
    },
    status: 0,
  },
  {
    name: 'TypeScript untokenizable input is reported with its location',
    files: { 'comment.ts': ['const a = 1', '/* open'], 'string.ts': ['const a = "abc'] },
    status: 2,
    stderr: [
      "comment.ts:3:1: cannot check TypeScript: '*/' expected.",
      'string.ts:1:15: cannot check TypeScript: Unterminated string literal.',
    ],
  },
  {
    name: 'Go comments are reported, including a spaced go: prefix, misplaced or unknown directives, malformed or indented line directives and a late generated marker',
    files: {
      'bad.go': ['package main', '', '// line', 'func main() {} /* block */', '// go:build linux'],
      'late.go': ['package main', '', '// Code generated by tool; DO NOT EDIT.'],
      'line.go': [
        'package main',
        '',
        '\t//line indented.go:1',
        '//line missing-number.go',
        'var x = /*line zero.go:0*/ 1',
        'var y = /*line column.go:1:0*/ 2',
        'var z = /*line multi.go:1',
        '*/ 3',
      ],
      'misplaced.go': ['package main', '', 'var x = 1 //go:build linux', '', '//go:note text', 'func main() {}'],
    },
    status: 1,
    stdout: [
      'bad.go:3:1: Go comment',
      'bad.go:4:16: Go comment',
      'bad.go:5:1: Go comment',
      'late.go:3:1: Go comment',
      'line.go:3:2: Go comment',
      'line.go:4:1: Go comment',
      'line.go:5:9: Go comment',
      'line.go:6:9: Go comment',
      'line.go:7:9: Go comment',
      'misplaced.go:3:11: Go comment',
      'misplaced.go:5:1: Go comment',
    ],
  },
  {
    name: 'Go strings, raw strings and runes are not comments',
    files: {
      'clean.go': [
        'package main',
        '',
        'var (',
        '\ts = "http://x // y /* z */"',
        '\tr = `raw // text',
        '/* still raw */`',
        "\tc = '/'",
        "\tq = '\\''",
        '\te = "\\"//"',
        ')',
      ],
    },
    status: 0,
  },
  {
    name: 'Go directives, line directives and generated files are allowed',
    files: {
      'directives.go': [
        '//go:build linux',
        '',
        'package main',
        '',
        'import _ "embed"',
        '',
        '//go:embed x.txt',
        'var data string',
        '',
        '//go:generate echo generate',
        '//go:noinline',
        'func main() {}',
        '',
        'type t struct{}',
        '',
        '\t//go:noinline',
        'func (t) f() {}',
        '',
        '//line generated.go:40',
        'func g() {}',
        '',
        'var v = /*line generated.go:50:3*/ 1',
        '',
        '//line :60:1',
        'func h() {}',
        '',
        '//line C:\\gen\\windows.go:70',
        'func w() {}',
      ],
      'generated.go': ['// Code generated by tool; DO NOT EDIT.', '', 'package main', '', '// comment', 'func f() {}'],
    },
    status: 0,
  },
  {
    name: 'Go untokenizable input is reported with its location',
    files: {
      'comment.go': ['package main', '/* open'],
      'raw.go': ['package main', 'var s = `abc'],
      'rune.go': ['package main', "var r = '\\"],
      'string.go': ['package main', 'var s = "abc'],
    },
    status: 2,
    stderr: [
      'comment.go:2:1: cannot check Go: unterminated comment',
      'raw.go:2:9: cannot check Go: unterminated raw string literal',
      'rune.go:2:9: cannot check Go: unterminated rune literal',
      'string.go:2:9: cannot check Go: unterminated string literal',
    ],
  },
  {
    name: 'SQL line and block comments are reported, including between parameters and after identifiers with $',
    files: {
      'bad.sql': [
        '-- leading',
        'SELECT 1--2',
        'FROM t /* block */;',
        "SELECT $name(') /* parameter */ , $other(');",
        'CREATE TABLE t(c my$type(/* type */ 10));',
        'SELECT :plain/* after parameter */;',
      ],
    },
    status: 1,
    stdout: [
      'bad.sql:1:1: SQL comment',
      'bad.sql:2:9: SQL comment',
      'bad.sql:3:8: SQL comment',
      'bad.sql:4:17: SQL comment',
      'bad.sql:5:26: SQL comment',
      'bad.sql:6:14: SQL comment',
    ],
  },
  {
    name: 'SQL string literals, quoted identifiers and parameters are not comments',
    files: {
      'clean.sql': [
        "SELECT '--', '/* */', 'it''s -- fine', \"--column\", [--bracketed], `--backticked`",
        'FROM t;',
        'SELECT $name(/*text*/), @p(--x), :q(/*y*/), #h(/*w*/), $a::b(--z), ?1;',
      ],
    },
    status: 0,
  },
  {
    name: 'SQL untokenizable input is reported with its location',
    files: {
      'comment.sql': ['SELECT 1 /* open'],
      'identifier.sql': ['SELECT [abc'],
      'parameter.sql': ['SELECT $a(b c)'],
      'string.sql': ["SELECT 'abc"],
    },
    status: 2,
    stderr: [
      'comment.sql:1:10: cannot check SQL: unterminated comment',
      'identifier.sql:1:8: cannot check SQL: unterminated quoted identifier',
      'parameter.sql:1:8: cannot check SQL: unterminated parameter',
      'string.sql:1:8: cannot check SQL: unterminated string literal',
    ],
  },
  {
    name: 'YAML comments are reported',
    files: {
      'bad.yaml': [
        '%YAML 1.2 # directive',
        '---',
        '# full line',
        'key: value # trailing',
        'list: [a, b] # after flow',
        'block: | # header',
        '  text',
      ],
    },
    status: 1,
    stdout: [
      'bad.yaml:1:11: YAML comment',
      'bad.yaml:3:1: YAML comment',
      'bad.yaml:4:12: YAML comment',
      'bad.yaml:5:14: YAML comment',
      'bad.yaml:6:10: YAML comment',
    ],
  },
  {
    name: 'YAML quoted and block scalars and # without preceding whitespace are not comments',
    files: {
      'clean.yml': [
        'plain: a#b',
        'url: http://h/#f',
        'double: "x # y"',
        "single: 'x # y'",
        'script: |',
        '  # shell comment is scalar content',
        '  echo hi',
        'folded: >',
        '  # also content',
      ],
    },
    status: 0,
  },
  {
    name: 'YAML untokenizable or structurally invalid input is reported with its location',
    files: { 'nested.yaml': ['a: b', '  c: d'], 'quote.yaml': ['key: "abc'] },
    status: 2,
    stderr: [
      'nested.yaml:1:4: cannot check YAML: Nested mappings are not allowed in compact mappings',
      'quote.yaml:2:1: cannot check YAML: Missing closing "quote',
    ],
  },
  {
    name: 'Dockerfile comments are reported, including indented ones and those between continued lines',
    files: {
      Dockerfile: ['# header', 'FROM node:26-slim', '  # indented', 'RUN echo a \\', '# between continued lines', '  && echo b'],
      'stage.Dockerfile': ['FROM scratch', '', '# syntax=docker/dockerfile:1'],
    },
    status: 1,
    stdout: [
      'Dockerfile:1:1: Dockerfile comment',
      'Dockerfile:3:3: Dockerfile comment',
      'Dockerfile:5:1: Dockerfile comment',
      'stage.Dockerfile:3:1: Dockerfile comment',
    ],
  },
  {
    name: 'Dockerfile leading parser directives, # inside instructions and heredoc bodies are not Dockerfile comments',
    files: {
      Dockerfile: [
        '# syntax=docker/dockerfile:1',
        '#ESCAPE = \\',
        'FROM node:26-slim',
        'RUN echo "#1" && echo a#b # shell',
        'RUN <<EOF',
        '# shell script',
        'echo hi',
        'EOF',
        'COPY <<-"CONFIG" <<FILE /etc/',
        '\t# file content',
        '\tCONFIG',
        '# second file',
        'FILE',
        'LABEL x=y',
      ],
    },
    status: 0,
  },
  {
    name: 'Dockerfile heredocs open only as words of RUN, COPY and ADD in shell form and start after the continued line',
    files: {
      Dockerfile: [
        'FROM node:26-slim',
        'LABEL example="<<EOF"',
        '# after a quoted label value',
        'RUN echo "<<EOF" \'<<EOF\' \\<<EOF cat<<EOF <<<EOF',
        '# after operators inside words',
        'CMD cat <<EOF',
        '# after an instruction without heredocs',
        'RUN ["sh", "-c", "cat <<EOF"]',
        '# after the exec form',
        'ONBUILD COPY --chown=node ["<<EOF", "/x"]',
        '# after the exec form of a trigger',
        'RUN --mount=type=cache,target=/x cat <<EOF \\',
        '# between continued lines',
        'EOF \\',
        "  && cat 3<<'E F'",
        '# first body',
        'EOF',
        '# second body',
        'E F',
        '# after the bodies',
        'onbuild run cat <<-"EOF"',
        '\t# trigger body',
        '\tEOF',
        '# last',
      ],
      'escape.Dockerfile': ['# escape=`', 'FROM scratch', 'RUN cat <<EOF `', 'EOF', '# body', 'EOF', '# after the body'],
    },
    status: 1,
    stdout: [
      'Dockerfile:3:1: Dockerfile comment',
      'Dockerfile:5:1: Dockerfile comment',
      'Dockerfile:7:1: Dockerfile comment',
      'Dockerfile:9:1: Dockerfile comment',
      'Dockerfile:11:1: Dockerfile comment',
      'Dockerfile:13:1: Dockerfile comment',
      'Dockerfile:20:1: Dockerfile comment',
      'Dockerfile:24:1: Dockerfile comment',
      'escape.Dockerfile:7:1: Dockerfile comment',
    ],
  },
  {
    name: 'Dockerfile with an unterminated heredoc is reported at its instruction',
    files: { Dockerfile: ['FROM scratch', 'RUN <<EOF', 'echo hi'], 'continued.Dockerfile': ['FROM scratch', 'RUN cat \\', '  <<EOF'] },
    status: 2,
    stderr: [
      'Dockerfile:2:1: cannot check Dockerfile: unterminated heredoc',
      'continued.Dockerfile:2:1: cannot check Dockerfile: unterminated heredoc',
    ],
  },
  {
    name: '.dockerignore comments are reported, and # after the first column is a pattern',
    files: {
      '.dockerignore': ['# comment', 'node_modules', ' #pattern', 'a#b'],
      'solver.Dockerfile.dockerignore': ['dist', '#comment'],
    },
    status: 1,
    stdout: ['.dockerignore:1:1: dockerignore comment', 'solver.Dockerfile.dockerignore:2:1: dockerignore comment'],
  },
  {
    name: 'CSS comments are reported, including after hash and at-keyword names',
    files: {
      'bad.css': [
        '/* header */',
        'a /* selector */ b { color: red /* value */; }',
        'c { color: #url(/* hash */); }',
        '@url(/* at-keyword */);',
      ],
    },
    status: 1,
    stdout: [
      'bad.css:1:1: CSS comment',
      'bad.css:2:3: CSS comment',
      'bad.css:2:33: CSS comment',
      'bad.css:3:17: CSS comment',
      'bad.css:4:6: CSS comment',
    ],
  },
  {
    name: 'CSS strings, url() with plain or escaped names and escapes are not comments',
    files: {
      'clean.css': [
        'a { content: "/* no */"; background: url(http://x//y/*z*/); }',
        "b { content: '\\'/*'; background: url( \"http://z/*q*/\" ); }",
        'c { background: url(a\\)/*b*/); }',
        '.w-1\\/2, .\\/*d { width: 50%; }',
        'e { background: u\\72l(http://host/*x*/); }',
        'f { background: \\55 R\\l(http://host/*y*/); }',
      ],
    },
    status: 0,
  },
  {
    name: 'CSS untokenizable input is reported with its location',
    files: {
      'comment.css': ['a { } /* open'],
      'string.css': ['a { content: "abc', '}'],
      'url.css': ['a { background: url(abc'],
    },
    status: 2,
    stderr: [
      'comment.css:1:7: cannot check CSS: unterminated comment',
      'string.css:1:14: cannot check CSS: unterminated string',
      'url.css:1:17: cannot check CSS: unterminated url',
    ],
  },
  {
    name: 'JSON comments are reported',
    files: { 'bad.json': ['{', '  // line', '  "a": 1 /* block */', '}'] },
    status: 1,
    stdout: ['bad.json:2:3: JSON comment', 'bad.json:3:10: JSON comment'],
  },
  {
    name: 'JSON strings are not comments',
    files: { 'clean.json': ['{ "url": "http://x", "block": "/* x */", "hash": "# y" }'] },
    status: 0,
  },
  {
    name: 'JSON untokenizable input is reported with its location',
    files: { 'comment.json': ['{ "a": 1 /* open'], 'string.json': ['{ "a": "b', '}'] },
    status: 2,
    stderr: [
      "comment.json:2:1: cannot check JSON: '*/' expected.",
      'string.json:1:10: cannot check JSON: Unterminated string literal.',
    ],
  },
]

const lineEndings = [
  { name: 'LF', eol: '\n' },
  { name: 'CRLF', eol: '\r\n' },
] as const

const runs = cases.flatMap((languageCase) =>
  lineEndings.map((lineEnding) => ({ ...languageCase, title: `${languageCase.name} (${lineEnding.name})`, eol: lineEnding.eol })),
)

test.concurrent.for(runs)('$title', async (run, { expect, onTestFinished }) => {
  const root = await createWorkspace(
    onTestFinished,
    Object.fromEntries(Object.entries(run.files).map(([path, lines]) => [path, `${lines.join(run.eol)}${run.eol}`])),
  )

  const result = await runCli(root, ['.'])

  expect(result).toEqual({ status: run.status, stdout: run.stdout ?? [], stderr: run.stderr ?? [] })
})
