import { test } from 'vitest'
import { createWorkspace, runCli } from './cli.js'

interface LanguageCase {
  readonly name: string
  readonly files: Readonly<Record<string, readonly string[]>>
  readonly status: number
  readonly stdout?: readonly string[]
  readonly stderr?: readonly string[]
}

const cases: readonly LanguageCase[] = [
  {
    name: 'TypeScript comments of every kind are reported',
    files: {
      'bad.ts': [
        '// @ts-expect-error',
        "const a: number = 'x'",
        '/** JSDoc */',
        'export const b = a /* trailing */',
        '/* c8 ignore next */',
        '// eslint-disable-next-line',
        'export const c = `${b /* inside */}`',
        '/// <reference types="node" />',
      ],
      'bad.tsx': ['export const A = () => (', '  <div>', '    {/* jsx */}', '  </div>', ')'],
      'bad.mjs': ['/** @type {number} */', 'export const d = 1'],
    },
    status: 1,
    stdout: [
      'bad.mjs:1:1: JavaScript comment',
      'bad.ts:1:1: TypeScript comment',
      'bad.ts:3:1: TypeScript comment',
      'bad.ts:4:20: TypeScript comment',
      'bad.ts:5:1: TypeScript comment',
      'bad.ts:6:1: TypeScript comment',
      'bad.ts:7:23: TypeScript comment',
      'bad.ts:8:1: TypeScript comment',
      'bad.tsx:3:6: TypeScript comment',
    ],
  },
  {
    name: 'TypeScript and JavaScript strings, templates, regexes and JSX text are not comments',
    files: {
      'clean.ts': [
        'const url = "http://x"',
        "const block = '/* x */'",
        'const template = `/* x */ ${url} // y`',
        'const regex = /\\/\\/x/',
        'const ratio = 4 / 2 / 1',
        'export { url, block, template, regex, ratio }',
      ],
      'clean.jsx': ['export const A = () => <a href="http://x">// text /* text */</a>'],
      'clean.cjs': ['module.exports = { pattern: /[/*]/g, escaped: "\\"//" }'],
    },
    status: 0,
  },
  {
    name: 'TypeScript shebang and leading reference directives are allowed',
    files: {
      'allowed.ts': [
        '#!/usr/bin/env node',
        '/// <reference types="node" />',
        '/// <reference lib="es2025" />',
        'export {}',
      ],
      'allowed.mjs': ['#!/usr/bin/env node', 'export {}'],
    },
    status: 0,
  },
  {
    name: 'TypeScript untokenizable input is reported with its location',
    files: { 'comment.ts': ['const a = 1', '/* open'], 'string.ts': ['const a = "abc'] },
    status: 2,
    stderr: [
      "comment.ts:3:1: cannot check TypeScript: '*/' expected.",
      'string.ts:1:15: cannot check TypeScript: Unterminated string literal.',
    ],
  },
  {
    name: 'Go comments are reported, including a spaced go: prefix and a late generated marker',
    files: {
      'bad.go': ['package main', '', '// line', 'func main() {} /* block */', '// go:build linux'],
      'late.go': ['package main', '', '// Code generated by tool; DO NOT EDIT.'],
    },
    status: 1,
    stdout: ['bad.go:3:1: Go comment', 'bad.go:4:16: Go comment', 'bad.go:5:1: Go comment', 'late.go:3:1: Go comment'],
  },
  {
    name: 'Go strings, raw strings and runes are not comments',
    files: {
      'clean.go': [
        'package main',
        '',
        'var (',
        '\ts = "http://x // y /* z */"',
        '\tr = `raw // text',
        '/* still raw */`',
        "\tc = '/'",
        "\tq = '\\''",
        '\te = "\\"//"',
        ')',
      ],
    },
    status: 0,
  },
  {
    name: 'Go directives and generated files are allowed',
    files: {
      'directives.go': [
        '//go:build linux',
        '',
        'package main',
        '',
        '//go:generate echo generate',
        '//go:noinline',
        'func main() {}',
      ],
      'generated.go': ['// Code generated by tool; DO NOT EDIT.', '', 'package main', '', '// comment', 'func f() {}'],
    },
    status: 0,
  },
  {
    name: 'Go untokenizable input is reported with its location',
    files: {
      'comment.go': ['package main', '/* open'],
      'raw.go': ['package main', 'var s = `abc'],
      'rune.go': ['package main', "var r = '\\"],
      'string.go': ['package main', 'var s = "abc'],
    },
    status: 2,
    stderr: [
      'comment.go:2:1: cannot check Go: unterminated comment',
      'raw.go:2:9: cannot check Go: unterminated raw string literal',
      'rune.go:2:9: cannot check Go: unterminated rune literal',
      'string.go:2:9: cannot check Go: unterminated string literal',
    ],
  },
  {
    name: 'SQL line and block comments are reported',
    files: { 'bad.sql': ['-- leading', 'SELECT 1--2', 'FROM t /* block */;'] },
    status: 1,
    stdout: ['bad.sql:1:1: SQL comment', 'bad.sql:2:9: SQL comment', 'bad.sql:3:8: SQL comment'],
  },
  {
    name: 'SQL string literals and quoted identifiers are not comments',
    files: {
      'clean.sql': [
        "SELECT '--', '/* */', 'it''s -- fine', \"--column\", [--bracketed], `--backticked`",
        'FROM t;',
      ],
    },
    status: 0,
  },
  {
    name: 'SQL untokenizable input is reported with its location',
    files: {
      'comment.sql': ['SELECT 1 /* open'],
      'identifier.sql': ['SELECT [abc'],
      'string.sql': ["SELECT 'abc"],
    },
    status: 2,
    stderr: [
      'comment.sql:1:10: cannot check SQL: unterminated comment',
      'identifier.sql:1:8: cannot check SQL: unterminated quoted identifier',
      'string.sql:1:8: cannot check SQL: unterminated string literal',
    ],
  },
  {
    name: 'YAML comments are reported',
    files: {
      'bad.yaml': [
        '%YAML 1.2 # directive',
        '---',
        '# full line',
        'key: value # trailing',
        'list: [a, b] # after flow',
        'block: | # header',
        '  text',
      ],
    },
    status: 1,
    stdout: [
      'bad.yaml:1:11: YAML comment',
      'bad.yaml:3:1: YAML comment',
      'bad.yaml:4:12: YAML comment',
      'bad.yaml:5:14: YAML comment',
      'bad.yaml:6:10: YAML comment',
    ],
  },
  {
    name: 'YAML quoted and block scalars and # without preceding whitespace are not comments',
    files: {
      'clean.yml': [
        'plain: a#b',
        'url: http://h/#f',
        'double: "x # y"',
        "single: 'x # y'",
        'script: |',
        '  # shell comment is scalar content',
        '  echo hi',
        'folded: >',
        '  # also content',
      ],
    },
    status: 0,
  },
  {
    name: 'YAML untokenizable or structurally invalid input is reported with its location',
    files: { 'nested.yaml': ['a: b', '  c: d'], 'quote.yaml': ['key: "abc'] },
    status: 2,
    stderr: [
      'nested.yaml:1:4: cannot check YAML: Nested mappings are not allowed in compact mappings',
      'quote.yaml:2:1: cannot check YAML: Missing closing "quote',
    ],
  },
  {
    name: 'CSS comments are reported',
    files: { 'bad.css': ['/* header */', 'a /* selector */ b { color: red /* value */; }'] },
    status: 1,
    stdout: ['bad.css:1:1: CSS comment', 'bad.css:2:3: CSS comment', 'bad.css:2:33: CSS comment'],
  },
  {
    name: 'CSS strings, url() and escapes are not comments',
    files: {
      'clean.css': [
        'a { content: "/* no */"; background: url(http://x//y/*z*/); }',
        "b { content: '\\'/*'; background: url( \"http://z/*q*/\" ); }",
        'c { background: url(a\\)/*b*/); }',
        '.w-1\\/2, .\\/*d { width: 50%; }',
      ],
    },
    status: 0,
  },
  {
    name: 'CSS untokenizable input is reported with its location',
    files: {
      'comment.css': ['a { } /* open'],
      'string.css': ['a { content: "abc', '}'],
      'url.css': ['a { background: url(abc'],
    },
    status: 2,
    stderr: [
      'comment.css:1:7: cannot check CSS: unterminated comment',
      'string.css:1:14: cannot check CSS: unterminated string',
      'url.css:1:17: cannot check CSS: unterminated url',
    ],
  },
  {
    name: 'JSON comments are reported',
    files: { 'bad.json': ['{', '  // line', '  "a": 1 /* block */', '}'] },
    status: 1,
    stdout: ['bad.json:2:3: JSON comment', 'bad.json:3:10: JSON comment'],
  },
  {
    name: 'JSON strings are not comments',
    files: { 'clean.json': ['{ "url": "http://x", "block": "/* x */", "hash": "# y" }'] },
    status: 0,
  },
  {
    name: 'JSON untokenizable input is reported with its location',
    files: { 'comment.json': ['{ "a": 1 /* open'], 'string.json': ['{ "a": "b', '}'] },
    status: 2,
    stderr: [
      "comment.json:2:1: cannot check JSON: '*/' expected.",
      'string.json:1:10: cannot check JSON: Unterminated string literal.',
    ],
  },
]

const lineEndings = [
  { name: 'LF', eol: '\n' },
  { name: 'CRLF', eol: '\r\n' },
] as const

const runs = cases.flatMap((languageCase) =>
  lineEndings.map((lineEnding) => ({ ...languageCase, title: `${languageCase.name} (${lineEnding.name})`, eol: lineEnding.eol })),
)

test.concurrent.for(runs)('$title', async (run, { expect, onTestFinished }) => {
  const root = await createWorkspace(
    onTestFinished,
    Object.fromEntries(Object.entries(run.files).map(([path, lines]) => [path, `${lines.join(run.eol)}${run.eol}`])),
  )

  const result = await runCli(root, ['.'])

  expect(result).toEqual({ status: run.status, stdout: run.stdout ?? [], stderr: run.stderr ?? [] })
})
